---
title: "HydroEnR"
author: "Jonathan Payne"
date: "14/06/2022"
output: html_document
---

# Welcome to HydroEnR

This package is designed for members of Evidence and Risk. It allows you to;

* Easily load data from WISKI  
  * Carry out checks on these data sets  
* Aggregate data by different periods and through various functions using rapid C++ elements 
* Detect peaks in hydrological data
* Convert flow data to a volumetric measure over a designated time step
* Develop Thiessen polygons for use in our realtime flood forecast models
* Download up-to-date meta data on EA gauges
* Import recent flow, stage and rain gauge data via the EAs API
* Detect trends in hydrological data
* Inspect ARMA parameters for stability in a real time forecasting context
* Use basic hydraulic equations such as the Mannings' equation
  * Import cross sectional data and carry out rudimentry analyses 
* Carry out single site analyses
  * ESS in the near future
* Use a greater selction of objective functions during model calibration

