# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

signDblCPP <- function(x) {
    .Call('_HydroEnR_signDblCPP', PACKAGE = 'HydroEnR', x)
}

#' @title Find peaks in hydrological data
#' @description Tested to be 6x faster, 37 us vs 207 us. This operation is done from 200x per layer. Original R function by Stas_G
#' @param vY Numeric vector of hydrological data
#' @param m Window over which to determine peaks
#' @export
findPeaksCPP <- function(vY, m = 3L) {
    .Call('_HydroEnR_findPeaksCPP', PACKAGE = 'HydroEnR', vY, m)
}

#' @title Ffind peaks using C++
#' @param vY Numeric vector or timeseries
#' @param m Defaults as 3, set this to define window over which to determine peaks
#' [[Rcpp::export]]
NULL

gibbs_cpp <- function(N, thin) {
    .Call('_HydroEnR_gibbs_cpp', PACKAGE = 'HydroEnR', N, thin)
}

#' @title Basic pareto based PDM in R
#' @param fc Rainfac, adjust to apply multiplier against rainfall
#' @param Cmin Minimum soil storage
#' @param Cmax Maximum soil storage
#' @export
PDM <- function(fc, Cmin, Cmax, b, P, PE, s, be, kg, St, bg, k1, k2, kb, area) {
    .Call('_HydroEnR_PDM', PACKAGE = 'HydroEnR', fc, Cmin, Cmax, b, P, PE, s, be, kg, St, bg, k1, k2, kb, area)
}

