# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

signDblCPP <- function(x) {
    .Call('_HydroEnR_signDblCPP', PACKAGE = 'HydroEnR', x)
}

findPeaksCPP <- function(vY, m = 3L) {
    .Call('_HydroEnR_findPeaksCPP', PACKAGE = 'HydroEnR', vY, m)
}

